### ISSUE TITLE
Repaint/re-calcute the grid programmatically

### ISSUE THREAD

**Issue by i8ramin** [Margaux7/react-masonry-list#11]
We are loading a grid of cards with variable heights (which are not known at time of initial render). Once the images load, we use the width/height data (from the onLoad listener) to set the aspect ratio of the card. We would like to re-render or repaint the masonry list when this happens, programmatically. Is this possible?

**Comment by Margaux7** [comment]
Do you mean that the aspect ratio of the card is exactlty the same as the image?  If you check my source code, you will find that the height of every grid element is calculated exactly in the img onload listener, which ensures the correct aspect ratio, so I think you don't need to do this calculation by yourself. I think your requirement is exactly the same with my demo. Please refer to the  [demo code](https://github.com/Margaux7/react-masonry-list/tree/master/demo).

**Comment by Topgt** [comment]
我希望能 设置某个“item”  grid-row-end 和  grid-column-end 我应该怎么做
