### ISSUE TITLE
Inconsistent gap sizes

### ISSUE THREAD

**Issue by Alfiejz** [Margaux7/react-masonry-list#5]
There seems to be inconsistent vertical gap sizes. Is this a limitation from using css grid and dividing rows into smaller chunks?

**Comment by Margaux7** [comment]
Can you show something about your usage, current effect and the results you expect？I'm not very sure what the situation will lead to "inconsistent vertical gap size"

**Comment by Alfiejz** [comment]
I can only provide this [screenshot](https://imgur.com/zhKu6UT) since I didn't take any more while I was encountering issues. 
Ignore the much larger gap between the top two images, that is my fault since that one image isn't as wide as the others. But you can still see that the remaining three gaps are not equal. I was expecting them to all be the gap specified (8px or 10px).

Besides that, I mainly had problems with the gap sizes being inconsistent while changing the window dimensions. The gap updates were a bit 'laggy', but at certain window widths or zoom levels would visibly differ in sizes by quite a bit.

Sorry if I'm not very helpful! I used GatsbyJS and static images.

**Comment by binsmyth** [comment]
Is there any solution to this problem?

**Comment by Margaux7** [comment]
Hi guys, I tried to fix the issue and updated package, v1.0.2 should work perfactly, please let me know if you still have weird gap problem.

**Comment by binsmyth** [comment]
Thanks so much for that. I will try and see.
